### ISSUE TITLE
module 'twirl' has no attribute 'find_peaks'

### ISSUE THREAD

**Issue by mrobberto** [lgrcia/twirl#19]
## Bug Report

I am getting this error

>module 'twirl' has no attribute 'find_peaks'

that is not present with an earlier version of the code. 
## How To Reproduce

pip install twirl
python
import twirl
twirl.[TAB]

### Environment
* OS: macOS
## Additional context

**Comment by lgrcia** [comment]
Hi @mrobberto, thanks for reporting this issue.

As @michealroberts explains, the function has been dropped from the last version. The main reason was that I found the function simple enough to remove it it from `twirl` and omit the `photutils` dependency. Despite the <v1, I reckon the versioning wasn't perfectly rigorous.

Looking back at the readme (that contains the only reference to this function), I think it is still nice to have such a function available. I propose to make a `0.3.3` patch that will include the following function:

```python
# not tested - need docs
# -----------------------

from astropy.stats import sigma_clipped_stats
from photutils.segmentation import SourceFinder, SourceCatalog

def find_peaks(data, sigma=6):
  mean, median, std = sigma_clipped_stats(data, sigma=3.0) 
  segmented = SourceFinder(5)(data - median, sigma * std)
  cat = SourceCatalog(data, segmented)
  return (
      cat.to_table()
      .to_pandas()
      .sort_values("area", ascending=False)[["xcentroid", "ycentroid"]]
      .values
  )
```
and bring the `photutils` dependency back. Since it fixes a bug and brings back an omitted function, I think a patch is appropriate.

What do you think?

**Comment by mrobberto** [comment]
hi Lionel,
thank you for your prompt feedback! I think reinstating the function would be very nice to keep code already developed, and in my experience find_peaks works pretty nicely. Note that is used in the notebooks/demos. This is typically what people like me uses to get quickly out of the woods...
Thank you again
Massimo

**Comment by lgrcia** [comment]
Thanks for the feedback. `find_peaks` is back in [`0.3.3`](https://pypi.org/project/twirl/0.3.3/)!

You mentioned `notebooks/demos` which seems to reference an outdated version of the repository. Is this something you found on an old clone or something that is still online?

The documentation should be hosted on [twirl.readthedocs.io](https://twirl.readthedocs.io/) so I prefer to check we don't have alternative docs out there.
