### ISSUE TITLE
I'm curious for more detail about the project's motivations.

### ISSUE THREAD

**Issue by alexw-im** [lgrcia/twirl#29]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/lgrcia/twirl/issues?q=is%3Aissue).

## Question

I've just come across your project and I'm impressed by the polish - it really looks like you've put a ton of effort into it this year!

It made me very curious to know more about your underlying motivation. Of course I read right at the top that your goal is to take an image and its center RA/Dec, and compute a WCS for that image. But it seems to me like you've taken a perhaps more thorough than necessary approach to do that and I'm very curious why. Or maybe this is actually the path of least resistance?

First off, maybe my understanding of WCS is wrong - I'm not much of an astrophotographer (yet) so I'm not steeped in this stuff. I thought a WCS was basically a transformation matrix that would give you the image's RA, Dec, and orientation towards celestial north. Perhaps it includes distortion? I think maybe I read that somewhere?

You cite Lang et al, so presumably you made an active decision not to simply reuse Astrometry.net - what were those reasons? 

It's quite clear that this is not a lost in space solver - it looks like the primary limitation there is that you run online queries of the Gaia database that require internet access?

Anyway congratulations on a very neat and well put together package!

## Additional context

None

**Comment by lgrcia** [comment]
I really love that you've taken the time to ask all these questions, thanks a lot!

_Path of least resistance?_

The main motivation for this work was not even computing a WCS, but to find the affine transform between two images based on the coordinates of their respective sources. If you have a list of the same sources well sorted that’s fine. But if the two lists are of different sizes, unsorted and with missing entries, the algorithm implemented here really becomes necessary.

_Transform matrix + distortion?_

It can be seen as a transform matrix, you’re right. It allows to map from pixel to sky coordinates, so it also encapsulates part of the pixel properties (e.g. angular size) and much more (distorsion indeed).

_Why not to simply reuse Astrometry.net?_

Astrometry.net is for a different need, when a totally blind search is necessary, which is not often the case in Astronomy where we know where we point our telescopes to. I first found cumbersome (and very slow) to send my images over a server to do astrometry, or to download large catalogs to have it working locally (and even, it is slow because it searches blindly). Since my main motivation was really image alignment I thought of reimplementing the algorithm myself.

I could have copied the C code there or adapt the python wrapper, but I liked the idea of it being implemented in python and the lower-level algorithm being available as a package. I must say I am very impressed by their own memory-efficient implementation of kd-tree, but that is not quite necessary for the low number of asterisms we are dealing with here.

_It looks like the primary limitation there is that you run online queries of the Gaia database that require internet access?_

It is. Some ideas (@ppp-one) involved providing a very minimal Gaia catalog to work locally.

**Comment by alexw-im** [comment]
Very cool, thanks for the details! It's very easy to see "plate solving" and assume "that's the same problem I have" when in reality it's only very similar. I certainly agree that using nova.astrometry.net would have been perhaps lower effort, but certainly wildly worse in user experience. The minimum viable I think would have been for you to install it locally but that comes with all kinds of portability headaches, depending on where you want to use this package and who else you envision using it. 

Not that I think this project has much to gain, but perhaps you'd be interested to know of similar work as I've been collecting somewhat of a list while learning the space: https://github.com/esa/tetra3 and https://github.com/neuromorphicsystems/astrometry seem like they might interest you if you come across a need for more blind solving in the future.

**Comment by lgrcia** [comment]
Indeed, I didn't know about these codes. I will check them out! Thanks a lot for that
